#!/bin/bash


echo "Checking lint (using eslint)"

# if [ $(command -v eslint) ]
# then
#     echo "eslint is globally installed. using global version."
#     eslint --resolve-plugins-relative-to=$(npm root -g) -c ../.eslintrc.json "../src/"
# else
# echo "eslint is not globally installed. trying local version..."
echo "using local eslint"
../node_modules/eslint/bin/eslint.js "../src/"
# fi
