#!/bin/bash


echo "Checking lint (using eslint)"

if [ $(command -v eslint) ]
then
    echo "eslint is globally installed. using global version."
    eslint "../src/"
else
    echo "eslint is not globally installed. trying local version..."
    ../node_modules/eslint/bin/eslint.js "../src/"
fi
